export const TenseMapping: Record<string, string> = {
    "Infinitif": "infinitif",
    "Participe Passé": "participePasse",
    "Participe Présent": "participePresent",
    "Auxiliaire": "auxiliaire",
    "Forme Pronominale": "formePronominale",
    "Présent": "present",
    "Imparfait": "imparfait",
    "Passé Simple": "passeSimple",
    "Futur": "futurSimple",
    "Passé Composé": "passeCompose",
    "Plus-que-parfait": "plusQueParfait",
    "Passé Antérieur": "passeAnterieur",
    "Futur Antérieur": "futurAnterieur",
    "Subjonctif Présent": "subjonctifPresent",
    "Subjonctif Imparfait": "subjonctifImparfait",
    "Subjonctif Passé": "subjonctifPasse",
    "Subjonctif Plus-que-parfait": "subjonctifPlusQueParfait",
    "Conditionnel Présent": "conditionnelPresent",
    "Conditionnel Passé": "conditionnelPasse",
    "Conditionnel Passé II": "conditionnelPasseII",
    "Impératif Passé": "imperatifPasse",
  };